### ISSUE TITLE
Error: Timeout

### ISSUE THREAD

**Issue by yahia912** [Freddywhest/NotPixel#3]
Error: TIMEOUT
    at /home/yahi/NotPixel/node_modules/telegram/client/updates.js:250:85
    at async attempts (/home/yahi/NotPixel/node_modules/telegram/client/updates.js:234:20)
    at async _updateLoop (/home/yahi/NotPixel/node_modules/telegram/client/updates.js:183:17)

**Comment by Freddywhest** [comment]
Ignore this warning and keep the bot running
